name       : mycroft-core
version    : 19.02.14
release    : 3
source     :
    - https://github.com/MycroftAI/mycroft-core/archive/release/v19.2.14.tar.gz : be610c54770cd3faaca2ec57f8b7a8078cf659b8c408c47c25157ba3607b10a8
license    : Apache-2.0
component  : system.utils
homepage   : https://mycroft.ai
summary    : Mycroft Core, the Mycroft Artificial Intelligence platform.
description: |
    Mycroft is a hackable open source voice assistant.
builddeps  :
    - PyAudio
    - mimic
    - google-api-python-client
    - pep8
    - pyalsaaudio
    - pychromecast
    - python-adapt-parser
    - python-cryptography
    - python-dateutil
    - python-fann2
    - python-fasteners
    - python-gtts
    - python-gtts-token
    - python-inflection
    - python-msk
    - python-msm
    - python-padaos
    - python-padatious
    - python-petact
    - python-pillow
    - python-pocketsphinx
    - python-precise-runner
    - python-psutil
    - python-pulsectl
    - python-pyee
    - python-pyserial
    - python-requests
    - python-requests-futures
    - python-six
    - python-speech-recognition
    - python-tornado
    - python-vlc
    - python-websocket-client
    - python-xmlrunner
    - pyyaml

    - python-mock
    - python-pytest
rundeps    :
    - PyAudio
    - mimic
    - google-api-python-client
    - pep8
    - pyalsaaudio
    - pychromecast
    - python-adapt-parser
    - python-cryptography
    - python-dateutil
    - python-fann2
    - python-fasteners
    - python-gtts
    - python-gtts-token
    - python-inflection
    - python-msk
    - python-msm
    - python-padaos
    - python-padatious
    - python-petact
    - python-pillow
    - python-pocketsphinx
    - python-precise-runner
    - python-psutil
    - python-pulsectl
    - python-pyee
    - python-pyserial
    - python-requests
    - python-requests-futures
    - python-six
    - python-speech-recognition
    - python-tornado
    - python-vlc
    - python-websocket-client
    - python-xmlrunner
    - pyyaml
    - tensorflow # For the "precise" engine
setup      : |
    # No way we are allowing fixed versions!
    sed -i 's|==|>=|' requirements.txt

    %patch -p1 < $pkgfiles/0001-Make-it-stateless.patch
build      : |
    %python3_setup
install    : |
    %python3_install

    install -Dm00644 mycroft/configuration/mycroft.conf $installdir/usr/share/defaults/mycroft/mycroft.conf
    rm $installdir/usr/lib/python*/site-packages/mycroft/configuration/mycroft.conf

    install -Dm00644 $pkgfiles/mycroft-audio.service $installdir/usr/lib/systemd/user/mycroft-audio.service
    install -Dm00644 $pkgfiles/mycroft-bus.service $installdir/usr/lib/systemd/user/mycroft-bus.service
    install -Dm00644 $pkgfiles/mycroft-skills.service $installdir/usr/lib/systemd/user/mycroft-skills.service
    install -Dm00644 $pkgfiles/mycroft-voice.service $installdir/usr/lib/systemd/user/mycroft-voice.service
    install -Dm00644 $pkgfiles/mycroft.target $installdir/usr/lib/systemd/user/mycroft.target
check      : |
    cd mycroft-core*

    # Some test suites are skipped because they either require r/w access to /opt
    # or PulseAudio running.
    python3 -m pytest -s test/unittests -p no:warnings \
        --ignore=test/unittests/audio \
        --ignore=test/unittests/client \
        --ignore=test/unittests/skills
